package com.blifeinc.pinch_game.http

data class Finger3DDataDetail (
    var time: String,

    var wrist_x: Double,
    var wrist_y: Double,
    var wrist_z: Double,

    var thumb_cmc_x: Double,
    var thumb_cmc_y: Double,
    var thumb_cmc_z: Double,
    var thumb_mcp_x: Double,
    var thumb_mcp_y: Double,
    var thumb_mcp_z: Double,
    var thumb_ip_x: Double,
    var thumb_ip_y: Double,
    var thumb_ip_z: Double,
    var thumb_tip_x: Double,
    var thumb_tip_y: Double,
    var thumb_tip_z: Double,

    var index_finger_mcp_x: Double,
    var index_finger_mcp_y: Double,
    var index_finger_mcp_z: Double,
    var index_finger_pip_x: Double,
    var index_finger_pip_y: Double,
    var index_finger_pip_z: Double,
    var index_finger_dip_x: Double,
    var index_finger_dip_y: Double,
    var index_finger_dip_z: Double,
    var index_finger_tip_x: Double,
    var index_finger_tip_y: Double,
    var index_finger_tip_z: Double,

    var middle_finger_mcp_x: Double,
    var middle_finger_mcp_y: Double,
    var middle_finger_mcp_z: Double,
    var middle_finger_pip_x: Double,
    var middle_finger_pip_y: Double,
    var middle_finger_pip_z: Double,
    var middle_finger_dip_x: Double,
    var middle_finger_dip_y: Double,
    var middle_finger_dip_z: Double,
    var middle_finger_tip_x: Double,
    var middle_finger_tip_y: Double,
    var middle_finger_tip_z: Double,

    var ring_finger_mcp_x: Double,
    var ring_finger_mcp_y: Double,
    var ring_finger_mcp_z: Double,
    var ring_finger_pip_x: Double,
    var ring_finger_pip_y: Double,
    var ring_finger_pip_z: Double,
    var ring_finger_dip_x: Double,
    var ring_finger_dip_y: Double,
    var ring_finger_dip_z: Double,
    var ring_finger_tip_x: Double,
    var ring_finger_tip_y: Double,
    var ring_finger_tip_z: Double,

    var pinky_mcp_x: Double,
    var pinky_mcp_y: Double,
    var pinky_mcp_z: Double,
    var pinky_pip_x: Double,
    var pinky_pip_y: Double,
    var pinky_pip_z: Double,
    var pinky_dip_x: Double,
    var pinky_dip_y: Double,
    var pinky_dip_z: Double,
    var pinky_tip_x: Double,
    var pinky_tip_y: Double,
    var pinky_tip_z: Double

)